[build]
  command = "ls"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/roy33441/jedi"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200